services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.Symfony\Contracts\HttpClient\HttpClientInterface: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Company\Provider\CompanyProviderInterface:
        class: App\Company\Provider\DataHubCompanyProvider
        arguments:
            $client: '@test.Symfony\Contracts\HttpClient\HttpClientInterface'

    App\HistoricalQuotes\Fetcher\HistoricalQuotesFetcherInterface:
        class: App\HistoricalQuotes\Fetcher\RapidHistoricalDataFetcher
        arguments:
            $client: '@test.Symfony\Contracts\HttpClient\HttpClientInterface'
            $rapidApiKey: '123456'
